export const COUNTRY_MAP = {
  au: {
    id: 14,
    symbol: 'AUD',
    unit: 'AUD',
    name: 'Australia',
    code: 'au',
    image: '/static/img/flags/au.jpg',
    zipTips: 'Please enter 4 digits zipcode.',
    maxlength: 4,
    phoneLength: 9,
    phonePrefix: 61,
    isActive: false,
    zip_info: '^\\d{4}$',
  },
  bh: {
    id: 24,
    symbol: 'BHD',
    unit: 'BHD',
    name: 'Bahrain',
    code: 'bh',
    image: '/static/img/flags/bh.jpg',
    zipTips: 'Please enter 3-4 digits zipcode.',
    maxlength: 4,
    phoneLength: 8,
    phonePrefix: 973,
    isActive: false,
    zip_info: '^\\d{3,4}$',
  },
  bd: {
    id: 20,
    symbol: 'BDT',
    unit: 'BDT',
    name: 'Bangladesh',
    code: 'bd',
    image: '/static/img/flags/bd.jpg',
    zipTips: 'Please enter 4 digits zipcode.',
    maxlength: 4,
    phoneLength: 10,
    phonePrefix: 880,
    isActive: false,
    zip_info: '^\\d{4}$',
  },
  br: {
    id: 32,
    symbol: 'BRL',
    unit: 'BRL',
    name: 'Brazil',
    code: 'br',
    image: '/static/img/flags/br.jpg',
    zipTips: '8 or 9 digits. Numbers or - or space are allowed',
    noFirst: true,
    maxlength: 9,
    phoneLength: 9,
    phonePrefix: 55,
    isActive: false,
    zip_info: '^[\\d\\- ]{8,9}$',
  },
  ca: {
    id: 39,
    symbol: 'CAD',
    unit: 'CAD',
    name: 'Canada',
    code: 'ca',
    image: '/static/img/flags/ca.jpg',
    zipTips: '6 or 7 digits. Numbers or English characters or space are allowed',
    noFirst: true,
    maxlength: 7,
    phoneLength: 10,
    phonePrefix: 1,
    isActive: false,
    zip_info: '^[\\d\\w ]{6,7}$',
  },
  eg: {
    id: 66,
    symbol: 'EGP',
    unit: 'EGP',
    name: 'Egypt',
    code: 'eg',
    image: '/static/img/flags/eg.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 11,
    phonePrefix: 20,
    isActive: false,
    zip_info: '/^\\d{5}$/',
  },
  fr: {
    id: 76,
    symbol: 'EUR',
    unit: 'EUR',
    name: 'France',
    code: 'fr',
    image: '/static/img/flags/fr.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 10,
    phonePrefix: 33,
    isActive: false,
    zip_info: '^\\d{5}$',
  },
  in: {
    id: 105,
    symbol: '₹',
    unit: 'INR',
    name: 'India',
    code: 'in',
    image: '/static/img/flags/in.jpg',
    zipTips: 'Please enter 6 digits pincode.',
    maxlength: 6,
    phoneLength: 10,
    phonePrefix: 91,
    isActive: false,
    zip_info: '^\\d{6}$',
  },
  id: {
    id: 101,
    symbol: 'IDR',
    unit: 'IDR',
    name: 'Indonesia',
    code: 'id',
    image: '/static/img/flags/id.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 11,
    phonePrefix: 62,
    isActive: false,
    zip_info: '^\\d{5}$',
  },
  il: {
    id: 103,
    symbol: 'ILS',
    unit: 'ILS',
    name: 'Israel',
    code: 'il',
    image: '/static/img/flags/il.jpg',
    zipTips: 'Please enter 5 or 7 digits zipcode.',
    maxlength: 7,
    phoneLength: 9,
    phonePrefix: 972,
    isActive: false,
    zip_info: '(^\\d{5}$)|(^\\d{7}$)',
  },
  it: {
    id: 110,
    symbol: 'EUR',
    unit: 'EUR',
    name: 'Italy',
    code: 'it',
    image: '/static/img/flags/it.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 10,
    phonePrefix: 39,
    isActive: false,
    zip_info: '^.{0,12}$',
  },
  kw: {
    id: 123,
    symbol: 'KWD',
    unit: 'KWD',
    name: 'Kuwait',
    code: 'kw',
    image: '/static/img/flags/kw.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 8,
    phonePrefix: 965,
    isActive: false,
    zip_info: '^\\d{5}$',
  },
  lb: {
    id: 127,
    symbol: 'LBP',
    unit: 'LBP',
    name: 'Lebanon',
    code: 'lb',
    image: '/static/img/flags/lb.jpg',
    zipTips: '4,8 or 9 digits. Numbers or English characters or space are allowed',
    noFirst: true,
    maxlength: 9,
    phoneLength: 8,
    phonePrefix: 961,
    isActive: false,
    zip_info: '(^[\\d\\- ]{4}$)|(^[\\d\\- ]{8,9}$)',
  },
  my: {
    id: 158,
    symbol: 'MYR',
    unit: 'MYR',
    name: 'Malaysia',
    code: 'my',
    image: '/static/img/flags/my.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 10,
    phonePrefix: 60,
    isActive: false,
    zip_info: '^\\d{5}$',
  },
  mx: {
    id: 157,
    symbol: 'MXN',
    unit: 'MXN',
    name: 'Mexico',
    code: 'mx',
    image: '/static/img/flags/mx.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 10,
    phonePrefix: 52,
    isActive: true,
    zip_info: '^\\d{5}$',
  },
  om: {
    id: 173,
    symbol: 'OMR',
    unit: 'OMR',
    name: 'Oman',
    code: 'om',
    image: '/static/img/flags/om.jpg',
    zipTips: 'Please enter 3 digits zipcode.',
    maxlength: 3,
    phoneLength: 8,
    phonePrefix: 968,
    isActive: false,
    zip_info: '^\\d{3}$',
  },
  ph: {
    id: 178,
    symbol: 'PHP',
    unit: 'PHP',
    name: 'Philippines',
    code: 'ph',
    image: '/static/img/flags/ph.jpg',
    zipTips: 'Please enter 4 digits zipcode.',
    maxlength: 4,
    phoneLength: 10,
    phonePrefix: 63,
    isActive: false,
    zip_info: '^\\d{4}$',
  },
  qa: {
    id: 188,
    symbol: 'QAR',
    unit: 'QAR',
    name: 'Qatar',
    code: 'qa',
    image: '/static/img/flags/qa.jpg',
    phoneLength: 8,
    phonePrefix: 974,
    isActive: false,
  },
  sa: {
    id: 194,
    symbol: 'SAR',
    unit: 'SAR',
    name: 'Saudi Arabia',
    code: 'sa',
    image: '/static/img/flags/sa.jpg',
    phoneLength: 9,
    phonePrefix: 966,
    isActive: false,
  },
  sg: {
    id: 199,
    symbol: 'SGD',
    unit: 'SGD',
    name: 'Singapore',
    code: 'sg',
    image: '/static/img/flags/sg.jpg',
    zipTips: 'Please enter 6 digits zipcode.',
    maxlength: 6,
    phoneLength: 8,
    phonePrefix: 65,
    isActive: false,
    zip_info: '^\\d{6}$',
  },
  es: {
    id: 69,
    symbol: 'EUR',
    unit: 'EUR',
    name: 'Spain',
    code: 'es',
    image: '/static/img/flags/es.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 9,
    phonePrefix: 34,
    isActive: false,
    zip_info: '^\\d{5}$',
  },
  lk: {
    id: 130,
    symbol: 'LKR',
    unit: 'LKR',
    name: 'Sri Lanka',
    code: 'lk',
    image: '/static/img/flags/lk.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 9,
    phonePrefix: 94,
    isActive: false,
    zip_info: '^\\d{5}$',
  },
  th: {
    id: 219,
    symbol: 'THB',
    unit: 'THB',
    name: 'Thailand',
    code: 'th',
    image: '/static/img/flags/th.jpg',
    zipTips: 'Please enter 5 digits zipcode.',
    maxlength: 5,
    phoneLength: 9,
    phonePrefix: 66,
    isActive: false,
    zip_info: '^\\d{5}$',
  },
  ae: {
    id: 2,
    symbol: 'AED',
    unit: 'AED',
    name: 'United Arab Emirates',
    code: 'ae',
    image: '/static/img/flags/ae.jpg',
    phoneLength: 9,
    phonePrefix: 971,
    isActive: false,
  },
  gb: {
    id: 233,
    symbol: 'GBP',
    unit: 'GBP',
    name: 'United Kingdom',
    code: 'gb',
    image: '/static/img/flags/gb.jpg',
    zipTips: '5 or 8 digits. Numbers or English characters or space are allowed',
    noFirst: true,
    maxlength: 8,
    phoneLength: 10,
    phonePrefix: 44,
    isActive: false,
    zip_info: '^[\\d\\w ]{5,8}$',
  },
  us: {
    id: 235,
    symbol: 'USD',
    unit: 'USD',
    name: 'United States',
    code: 'us',
    image: '/static/img/flags/us.jpg',
    zipTips: '5,9 or 10 digits. Numbers or English characters or space are allowed',
    noFirst: true,
    maxlength: 10,
    phoneLength: 10,
    phonePrefix: 1,
    isActive: false,
    zip_info: '(^[\\d\\- ]{5}$)|(^[\\d\\- ]{9,10}$)',
  },
  vn: {
    id: 243,
    symbol: 'VND',
    unit: 'VND',
    name: 'Vietnam',
    code: 'vn',
    image: '/static/img/flags/vn.jpg',
    zipTips: 'Please enter 6 digits zipcode.',
    maxlength: 6,
    phoneLength: 10,
    phonePrefix: 84,
    isActive: false,
    zip_info: '^\\d{6}$',
  },
}
